# Generated by Django 3.0.6 on 2020-05-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=200)),
                ('youtube_etag', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=50)),
                ('publishedAt', models.DateField()),
                ('channelId', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('thumbnailsDefault', models.URLField()),
                ('thumbnailsHight', models.URLField()),
                ('channelTitle', models.TextField()),
                ('playlistId', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
                ('videoId', models.CharField(max_length=100)),
            ],
        ),
    ]
