# Generated by Django 3.0.6 on 2020-05-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20200522_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='youtube_etag',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
