# Generated by Django 3.0.6 on 2020-05-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_youtube_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=200)),
                ('razorpay_order_id', models.CharField(max_length=200, unique=True)),
                ('razorpay_signature', models.CharField(max_length=50)),
                ('currency', models.TextField()),
                ('amount', models.IntegerField(max_length=200)),
                ('order_id', models.TextField()),
            ],
        ),
    ]
