# Generated by Django 3.0.6 on 2020-05-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(max_length=500),
        ),
    ]
