# Generated by Django 3.0.6 on 2020-05-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_auto_20200527_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='entity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='error_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='error_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='error_reason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='error_source',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='error_step',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vpa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.TextField(null=True),
        ),
    ]
