# Generated by Django 3.0.6 on 2020-06-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200530_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coverImage',
            field=models.URLField(),
        ),
    ]
