from django.db import models

# Create your models here.

class Youtube(models.Model):
    youtube_id = models.CharField(max_length=200)
    youtube_etag = models.CharField(max_length=200, unique=True)
    kind = models.CharField(max_length=50)
    publishedAt = models.TextField()
    channelId = models.CharField(max_length=200)
    title = models.TextField()
    description = models.TextField()
    thumbnailsDefault = models.URLField(max_length=200)
    thumbnailsHight = models.URLField(max_length=200)
    channelTitle  = models.TextField()
    playlistId = models.CharField(max_length=200)
    position = models.IntegerField()
    videoId = models.CharField(max_length=100)
    stats_id = models.CharField(max_length=200, unique=True,default="null")
    stats_etag = models.CharField(max_length=200, unique=True, default="null")    
    viewCount = models.IntegerField(default=0)
    likeCount = models.IntegerField(default=0)
    dislikeCount = models.IntegerField(default=0)
    favoriteCount = models.IntegerField(default=0)
    commentCount = models.IntegerField(default=0)
    transcript  =  models.TextField(default="")



class Payment(models.Model):
    razorpay_payment_id = models.CharField(max_length=200)
    razorpay_order_id = models.CharField(max_length=200, unique=True)
    razorpay_signature = models.CharField(max_length=500)
    currency = models.TextField(null=True)
    amount = models.CharField(max_length=200,  null=True)
    entity =  models.CharField(max_length=200,  null=True)
    status =  models.CharField(max_length=200,  null=True)
    invoice_id =  models.CharField(max_length=200,  null=True)
    international = models.BooleanField(default=False)
    method = models.CharField(max_length=200,  null=True)
    captured =  models.BooleanField(default=False)
    description = models.TextField(null=True)
    card_id  =  models.CharField(max_length=200,  null=True)
    bank = models.CharField(max_length=200,  null=True)
    wallet = models.CharField(max_length=200,  null=True)
    vpa = models.CharField(max_length=200,  null=True)
    email  = models.EmailField(null=True)
    contact = models.CharField(max_length=200,  null=True)
    fee = models.CharField(max_length=200,  null=True)
    tax = models.CharField(max_length=200,  null=True)
    error_code = models.CharField(max_length=200,  null=True)
    error_description = models.CharField(max_length=200,  null=True)
    error_source = models.CharField(max_length=200,  null=True)
    error_step = models.CharField(max_length=200,  null=True)
    error_reason = models.CharField(max_length=200,  null=True)
