# Generated by Django 3.0.6 on 2020-06-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200602_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
