# Generated by Django 3.0.6 on 2020-06-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
