# Generated by Django 3.0.6 on 2020-06-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200602_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.CharField(default=models.CharField(max_length=1000), max_length=1000),
        ),
    ]
