# Generated by Django 3.0.6 on 2020-06-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('simple', 'simple'), ('intermediate', 'intermediate')], default='simple', max_length=20),
        ),
    ]
