# Generated by Django 3.0.6 on 2020-06-02 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0010_auto_20200527_1342'),
        ('quiz', '0015_auto_20200602_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='quiz_id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='quiz.Questions'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='video_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube.Youtube'),
        ),
    ]
