# Generated by Django 3.0.6 on 2020-06-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20200604_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='mark',
            field=models.BooleanField(default=False),
        ),
    ]
