# Generated by Django 3.0.6 on 2020-06-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20200604_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='questions',
            new_name='choice',
        ),
    ]
