# Generated by Django 3.0.6 on 2020-06-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20200604_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='choice',
            new_name='choices',
        ),
    ]
