# Generated by Django 3.0.6 on 2020-06-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_userquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='attempt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='lastAttemptTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
