# Generated by Django 3.0.6 on 2020-06-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_auto_20200606_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='passStatus',
            field=models.BooleanField(default=False),
        ),
    ]
