# Generated by Django 3.0.6 on 2020-06-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_userquiz_passstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='attemptTime',
            field=models.DateTimeField(null=True),
        ),
    ]
