# Generated by Django 3.0.6 on 2020-06-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20200608_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
    ]
