# Generated by Django 3.0.6 on 2020-06-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_userquiz_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='quiz_det',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quiz.Quiz'),
        ),
    ]
