# Generated by Django 3.0.6 on 2020-05-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calender',
            name='startDate',
            field=models.DateField(),
        ),
    ]
